name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]  # Specify Node.js version explicitly
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Print Node & npm version  # Debugging step
        run: |
          node --version
          npm --version
          
      - name: Install Dependencies
        run: |
          npm ci  # Use ci instead of install for cleaner installs
          npm list  # List installed packages for debugging
          
      - name: Run Tests
        run: |
          npm test -- --verbose  # Add verbose flag for more details
        env:
          CI: true  # Ensure CI environment is set
          
      - name: Upload test results  # Optional: Upload test results as artifacts
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage/
            junit.xml
            test-results.xml
